### ISSUE TITLE
Provide text alternatives for non-text content.  

### ISSUE THREAD

**Issue by mgifford** [donnabungard/accessibility#15]
I think that the important thing about non-text content is reminding the Author that they need to be clear on what they are trying to say.  A bar graph might tell a clear message to the author, but not necessarily to the user.  This may or may not be because of a limitation in the users abilities.  Not everyone can read maps for instance.

**Comment by donnabungard** [comment]
Updated to: Think inclusively about your media. Do more than only provide captions and other alternatives for multimedia; effectively communicate non-text content in such a way that gives it context and meaning. It's not only about sight, it's about educating the user as to what value the media provides.
